<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HJNZL000593" failures="1" tests="11" name="Default test" time="68.828" errors="0" timestamp="15 Dec 2023 11:29:53 GMT">
  <testcase classname="portfolio_test.user.TC06_ArtifactPage" name="VerifyLoadtime" time="0.023"/>
  <testcase classname="portfolio_test.user.TC06_ArtifactPage" name="VerifySSTATSAndIMPACTOfArtifact" time="0.611">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at portfolio_test.user.TC06_ArtifactPage.VerifySSTATSAndIMPACTOfArtifact(TC06_ArtifactPage.java:113)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- VerifySSTATSAndIMPACTOfArtifact -->
  <testcase classname="portfolio_test.user.TC06_ArtifactPage" name="VerifyMaturitySectionOfArtifact" time="0.027"/>
  <testcase classname="portfolio_test.user.TC06_ArtifactPage" name="VerifyKeyMaterialsSectionOfArtifact" time="0.337"/>
  <testcase classname="portfolio_test.user.TC06_ArtifactPage" name="VerifyEvidenceSectionOfArtifact" time="3.417"/>
  <testcase classname="portfolio_test.user.TC06_ArtifactPage" name="VerifyENHANCEMENTSSectionOfArtifact" time="28.939"/>
  <testcase classname="portfolio_test.user.TC06_ArtifactPage" name="VerifyBoMSectionOfArtifact" time="4.449"/>
  <testcase classname="portfolio_test.user.TC06_ArtifactPage" name="VerifySolutionPlaySectionOfArtifact" time="1.291"/>
  <testcase classname="portfolio_test.user.TC06_ArtifactPage" name="VerifyArtifactSectionOfArtifact" time="5.306"/>
  <testcase classname="portfolio_test.user.TC06_ArtifactPage" name="VerifyCatalogueOfferSectionOfArtifact" time="5.281"/>
  <testcase classname="portfolio_test.user.TC06_ArtifactPage" name="VerifySeeAllCustomerEvidenceSearchPageFromArtifactPage" time="5.586"/>
</testsuite> <!-- Default test -->
