<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HJNZL000593" failures="1" tests="9" name="Default test" time="99.274" errors="0" timestamp="11 Dec 2023 08:45:26 GMT">
  <testcase classname="portfolio_test.user.TC05_CatalogueOfferPage" name="VerifyAI_Summary_view_OnCatalogueOfferPage" time="14.755"/>
  <testcase classname="portfolio_test.user.TC05_CatalogueOfferPage" name="VerifySSTATSAndIMPACTOfCatalogueOffer" time="0.059">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at portfolio_test.user.TC05_CatalogueOfferPage.VerifySSTATSAndIMPACTOfCatalogueOffer(TC05_CatalogueOfferPage.java:104)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- VerifySSTATSAndIMPACTOfCatalogueOffer -->
  <testcase classname="portfolio_test.user.TC05_CatalogueOfferPage" name="VerifyMaturitySectionOfCatalogueOffer" time="0.021"/>
  <testcase classname="portfolio_test.user.TC05_CatalogueOfferPage" name="VerifyKeyMaterialsSectionOfCatalogueOffer" time="0.029"/>
  <testcase classname="portfolio_test.user.TC05_CatalogueOfferPage" name="VerifyEvidenceSectionOfCatalogueOffer" time="0.716"/>
  <testcase classname="portfolio_test.user.TC05_CatalogueOfferPage" name="VerifyENHANCEMENTSSectionOfCatalogueOffer" time="50.336"/>
  <testcase classname="portfolio_test.user.TC05_CatalogueOfferPage" name="VerifyBoMSectionOfCatalogueOffer" time="9.437"/>
  <testcase classname="portfolio_test.user.TC05_CatalogueOfferPage" name="VerifySolutionPlaySectionOfCatalogueOffer" time="0.823"/>
  <testcase classname="portfolio_test.user.TC05_CatalogueOfferPage" name="VerifySeeAllCustomerEvidenceSearchPageFromCatalogueOfferPage" time="8.799"/>
</testsuite> <!-- Default test -->
